# Nombre del workflow que aparecerá en la interfaz de GitHub
name: Aprendiendo GitHub Actions
# Nombre personalizado que se muestra en cada ejecución del workflow
run-name: ¡Estoy aprendiendo GitHub Actions!
# Evento que dispara el workflow (en este caso, cada push al repositorio)
on: [push]
# Define los trabajos que se ejecutarán
jobs:
  # Nombre del trabajo
  hola-mundo:
    # Sistema operativo donde se ejecutará el trabajo
    runs-on: ubuntu-latest
    # Lista de pasos que componen el trabajo
    steps:
      # Paso para clonar el código del repositorio
      - name: Checkout
        # Acción predefinida que descarga el código del repositorio
        uses: actions/checkout@v3
      # Paso para crear una variable de entorno
      - name: Definir variable
        # Define USERNAME con el nombre del usuario que hizo el push
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      # Paso para ejecutar el script de Python
      - name: Correr script
        # Ejecuta el archivo main.py con Python
        run: python main.py